import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconBook,
  IconList,
  IconUsers,
  IconHome,
  IconCards,
  IconShield,
  IconMail,
  IconFolder,
  IconFolderOpen,
  IconGlobe,
  IconChartBar,
  IconTrendingUp,
  IconCurrencyDollar,
  IconReceipt
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  // New icons for the menu structure
  book: IconBook,
  plus: IconPlus,
  list: IconList,
  users: IconUsers,
  userList: IconUsers,
  home: IconHome,
  card: IconCards,
  fileText: IconFileText,
  shield: IconShield,
  mail: IconMail,
  folder: IconFolder,
  folderOpen: IconFolderOpen,
  globe: IconGlobe,
  chartBar: IconChartBar,
  analytics: IconTrendingUp,
  dollarSign: IconCurrencyDollar,
  receipt: IconReceipt
};
